export const UPDATE_TOGGLE_VALUE = "UPDATE_TOGGLE_VALUE";
export const UPDATE_WEIGHING_INSTRUCTIONS_LIST =
    "UPDATE_WEIGHING_INSTRUCTIONS_LIST";

export const UPDATE_NOTES_INPUT_VALUE = "UPDATE_NOTES_INPUT_VALUE";